package Workshop2Project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.mindrot.jbcrypt.BCrypt;

public class User {

	private int id = 0;
	private String name;
	private String password;
	private String mail;
	private int personGroupId;

	public User(String name, String password, String mail, int personGroupID) {
		this.name = name;
		this.setPassword(password);
		this.mail = mail;
		this.personGroupId = personGroupID;
	}

	public void saveToDB(Connection conn) throws SQLException {
		if (this.id != 0) {
			String updateQuery = "INSERT INTO users(username, email, password, personGroupId) VALUES(?,?,?,?);";
			String[] autogenerated = new String[] { "id" };
			PreparedStatement preparedStatement;
			preparedStatement = conn.prepareStatement(updateQuery, autogenerated);
			preparedStatement.setString(1, this.name);
			preparedStatement.setString(2, this.mail);
			preparedStatement.setString(3, this.password);
			preparedStatement.setInt(4, personGroupId);
			preparedStatement.executeUpdate();
			ResultSet resSet = preparedStatement.getGeneratedKeys();
			while (resSet.next()) {
				this.id = resSet.getInt(1);
				System.out.println(resSet.getMetaData());
			}
		}
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = BCrypt.hashpw(password, BCrypt.gensalt());
	}

	public String getMail() {
		return mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public int getId() {
		return id;
	}

	public int getPersonGroupId() {
		return personGroupId;
	}

	public void setPersonGroupId(int personGroupId) {
		this.personGroupId = personGroupId;
	}

}
