package Workshop2Project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class UserGroup {

	private int id = 0;
	private String name;

	public UserGroup(String name) {
		this.name = name;
	}
	
	public void saveToDB(Connection conn) throws SQLException {
		if (this.id != 0) {
			String updateQuery = "INSERT INTO user_groups(name) VALUES(?);";
			String[] autogenerated = new String[] { "id" };
			PreparedStatement preparedStatement;
			preparedStatement = conn.prepareStatement(updateQuery, autogenerated);
			preparedStatement.setString(1, this.name);
			preparedStatement.executeUpdate();
			ResultSet resSet = preparedStatement.getGeneratedKeys();
			while (resSet.next()) {
				this.id = resSet.getInt(1);
				System.out.println(resSet.getMetaData());
			}
		}
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getId() {
		return id;
	}

}
